### ISSUE TITLE
Overwrite separator-border width?

### ISSUE THREAD

**Issue by svatkowski** [johnwalley/allotment#821]
Hi, im trying to modify the `separator-border` width but for some reasons, i coulnd't make it work well, is it possible via the style provided in the document?

**Comment by vipmax** [comment]
```css
:root {
  --sash-size: 10px;
  --sash-hover-size: 50px;
}

[class*="sash-module_sash_"]::before {
  background: gray !important;
}
```

This one works for me.
